name: Test with Testcontainers Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        
    - name: Cache Maven dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        
    # ✅ FIXED: Added TCC setup step
    # This establishes the connection to Testcontainers Cloud
    - name: Set up Testcontainers Cloud
      uses: atomicjar/testcontainers-cloud-setup-action@v1
      with:
        wait: true
        token: ${{ secrets.TESTCONTAINERS_CLOUD_TOKEN }}
        
    - name: Run tests
      run: mvn test
      env:
        # ✅ FIXED: Token is now properly configured with TCC agent
        TESTCONTAINERS_CLOUD_TOKEN: ${{ secrets.TESTCONTAINERS_CLOUD_TOKEN }}
