name: Publish LabSpace

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  publish:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push LabSpace
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: |
          your-dockerhub-username/tcc-lab:latest
          your-dockerhub-username/tcc-lab:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
