name: Test with Testcontainers Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install testcontainers[postgres] psycopg2-binary pytest
        
    # ❌ BROKEN: Missing TCC setup step
    # Customer expects tests to run in TCC but hasn't configured TCC agent
    
    - name: Run tests
      run: python -m pytest tests/ -v
      env:
        # ❌ BROKEN: Token is set but TCC agent not configured
        TESTCONTAINERS_CLOUD_TOKEN: ${{ secrets.TESTCONTAINERS_CLOUD_TOKEN }}
        
    # ❌ MISSING: TCC agent setup step
    # Should include:
    # - name: Set up Testcontainers Cloud
    #   uses: atomicjar/testcontainers-cloud-setup-action@v1
    #   with:
    #     wait: true
    #     token: ${{ secrets.TESTCONTAINERS_CLOUD_TOKEN }}
